// Compatibility helpers for the Accessibility methods generated by stock
// Hammerspoon 2. Some builds append argument labels to exported method names.

export function setAXAttribute(
  element: HSAXElement | null | undefined,
  name: string,
  value: unknown,
): boolean | undefined {
  const candidate = element as unknown as
    | {
        setAttributeValue?: (name: string, value: unknown) => boolean;
        setAttributeValueValue?: (name: string, value: unknown) => boolean;
      }
    | null
    | undefined;
  const setter = candidate && (candidate.setAttributeValue || candidate.setAttributeValueValue);
  return setter?.call(candidate, name, value);
}
